layout_spectrum: 0.28828885266557336
typography_spectrum: 0.018849482527002692
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.8475444468203932
  lightness: 0.04643850470893085
  saturation: 0.4110629386268556
  rhythmicContrast: 0.3618129803799093
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: gorgon
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: GORGON
description: where platonic horrors lurk
purpose: []
