typography_spectrum: 0.5962239902000874
color:
  brandColors: []
  brandStrength: 0.28032185859046876
  lightness: 0.35276737925596535
  saturation: 0.8174065223429352
  rhythmicContrast: 0.31483591767027974
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.42503
analytics:
  google: null
  facebook: null
  twitter: null
name: gorgon
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: GORGON
purpose: []
